sudo: required
language: python
  - "3.6.4"
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
install:
  - python3 -V
  - pip -V
  - sudo python3 -m pip install nose
script:
  - make test
